Update JenkinsfileBuild

diff --git a/Jenkins/JenkinsfileBuild b/Jenkins/JenkinsfileBuild
--- a/Jenkins/JenkinsfileBuild
+++ b/Jenkins/JenkinsfileBuild
@@ -111,22 +111,21 @@ pipeline {
             }
         }
 
-        post {
-            success {
-                echo '✅ Pipeline completed successfully.'
-            }
-            failure {
-                echo '❌ Pipeline failed. Cleaning up Docker images...'
-                script {
-                    def id = BUILD_NUMBER
-                    sh "docker rmi ${FRONTEND_IMAGE_NAME}:${id} || true"
-                    sh "docker rmi ${BACKEND_IMAGE_NAME}:${id} || true"
-                    sh "docker rmi ${UI_IMAGE_NAME}:${id} || true"
+    post {
+        success {
+            echo '✅ Pipeline completed successfully.'
+        }
+        failure {
+            echo '❌ Pipeline failed. Cleaning up Docker images...'
+            script {
+                def id = BUILD_NUMBER
+                sh "docker rmi ${FRONTEND_IMAGE_NAME}:${id} || true"
+                sh "docker rmi ${BACKEND_IMAGE_NAME}:${id} || true"
+                sh "docker rmi ${UI_IMAGE_NAME}:${id} || true"
 
-                    sh "sudo apt-get purge nodejs libnode72 -y"
-                    sh "sudo apt-get autoremove -y"
-                    sh "sudo apt-get update"
-                }
+                sh "sudo apt-get purge nodejs libnode72 -y"
+                sh "sudo apt-get autoremove -y"
+                sh "sudo apt-get update"
             }
         }
     }
